### ISSUE TITLE
Thank You For Making This Repository Public

### ISSUE THREAD

**Issue by O957** [CodexVeritas/forecasting-tools#1]
> Just decluttered some of the unecessary code, and made my private repo public [here](https://github.com/CodexVeritas/forecasting-tools). Still need to clean it up to be ready to be a package, but it has all the functionality.

Thank you very much for taking this action, and of course also for the work you've put in to the forecasting tools! This issue exist just to say Thank You and can be closed once read.

Thus far, I've played with your site to compete with the AI in Fermi estimation. Something I would like to see (my apologies if this already exists) is some way to make the underlying AI operate at different levels of ignorance. In asking it how many pianos Chicago has in 2024, some of the information it retrieved was quite specific. While I am not sure how this could be done, it would be nice if there was a feature to limit the information available to it about the world. 

I might make a PR adding `pre-commit` (see [here](https://github.com/pre-commit/pre-commit)), environment control with `poetry` (see [here](https://python-poetry.org/)), and an updated `.gitignore`. Let me know if you are completely against these measures; in this case I will not add any of the aforementioned elements.

**Comment by CodexVeritas** [comment]
Hey @AFg6K7h4fhy2! Thank you for the kind words!  Feel free to add those changes. Poetry was on my list of things to do, and I'm interested to experiment with pre-commit as I have not used it before (right now there are just settings in .vscode that apply the black formatter on file save).
